// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package socialmodels

import (
	"context"
	"database/sql"
	"easy_chat/pkg/constants"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendRequestsFieldNames          = builder.RawFieldNames(&FriendRequests{})
	friendRequestsRows                = strings.Join(friendRequestsFieldNames, ",")
	friendRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestsIdPrefix           = "cache:friendRequests:id:"
	cacheFriendRequestsUserIdReqUidPrefix = "cache:friendRequests:userId:reqUid:"
)

type (
	friendRequestsModel interface {
		Insert(ctx context.Context, data *FriendRequests) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*FriendRequests, error)
		FindOneByUserIdReqUid(ctx context.Context, userId string, reqUid string) (*FriendRequests, error)
		Update(ctx context.Context, data *FriendRequests) error
		Delete(ctx context.Context, id string) error
		UpdateHandleResult(ctx context.Context, session sqlx.Session, friendreqId string, handleResult int64) error
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		FindByTargetId(ctx context.Context, targetId string) ([]*FriendRequests, error)
	}

	defaultFriendRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequests struct {
		Id           string         `db:"id"`
		UserId       string         `db:"user_id"`       // 申请人ID（关联users.id）
		ReqUid       string         `db:"req_uid"`       // 被申请人ID（关联users.id）
		ReqMsg       string         `db:"req_msg"`       // 申请验证消息
		HandleResult int64          `db:"handle_result"` // 处理结果：0-待处理 1-同意 2-拒绝
		HandleUid    sql.NullString `db:"handle_uid"`    // 处理人ID（通常是req_uid）
		CreatedAt    time.Time      `db:"created_at"`    // 申请时间
		UpdatedAt    sql.NullTime   `db:"updated_at"`    // 处理时间
	}
)

func newFriendRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestsModel {
	return &defaultFriendRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_requests`",
	}
}

func (m *defaultFriendRequestsModel) Delete(ctx context.Context, id string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	friendRequestsUserIdReqUidKey := fmt.Sprintf("%s%v:%v", cacheFriendRequestsUserIdReqUidPrefix, data.UserId, data.ReqUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestsIdKey, friendRequestsUserIdReqUidKey)
	return err
}

func (m *defaultFriendRequestsModel) FindOne(ctx context.Context, id string) (*FriendRequests, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	var resp FriendRequests
	err := m.QueryRowCtx(ctx, &resp, friendRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) FindOneByUserIdReqUid(ctx context.Context, userId string, reqUid string) (*FriendRequests, error) {
	friendRequestsUserIdReqUidKey := fmt.Sprintf("%s%v:%v", cacheFriendRequestsUserIdReqUidPrefix, userId, reqUid)
	var resp FriendRequests
	err := m.QueryRowIndexCtx(ctx, &resp, friendRequestsUserIdReqUidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `req_uid` = ? limit 1", friendRequestsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, reqUid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) Insert(ctx context.Context, data *FriendRequests) (sql.Result, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	friendRequestsUserIdReqUidKey := fmt.Sprintf("%s%v:%v", cacheFriendRequestsUserIdReqUidPrefix, data.UserId, data.ReqUid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, friendRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ReqUid, data.ReqMsg, data.HandleResult, data.HandleUid)
	}, friendRequestsIdKey, friendRequestsUserIdReqUidKey)
	return ret, err
}

func (m *defaultFriendRequestsModel) Update(ctx context.Context, newData *FriendRequests) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	friendRequestsUserIdReqUidKey := fmt.Sprintf("%s%v:%v", cacheFriendRequestsUserIdReqUidPrefix, data.UserId, data.ReqUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ReqUid, newData.ReqMsg, newData.HandleResult, newData.HandleUid, newData.Id)
	}, friendRequestsIdKey, friendRequestsUserIdReqUidKey)
	return err
}
func (m *defaultFriendRequestsModel) UpdateHandleResult(ctx context.Context, session sqlx.Session, friendreqId string, handleResult int64) error {
	data, err := m.FindOne(ctx, friendreqId)
	if err != nil {
		return err
	}
	query := fmt.Sprintf("update %s set `handle_result`=? where `id`=?", m.table)
	_, err = session.ExecCtx(ctx, query, handleResult, friendreqId)
	if err != nil {
		return err
	}
	go func() {
		friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, friendreqId)
		friendRequestsUserIdReqUidKey := fmt.Sprintf("%s%v:%v", cacheFriendRequestsUserIdReqUidPrefix, data.UserId, data.ReqUid)
		_ = m.DelCacheCtx(context.Background(), friendRequestsIdKey, friendRequestsUserIdReqUidKey)
	}()
	return nil
}

func (m *defaultFriendRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, primary)
}

func (m *defaultFriendRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestsModel) tableName() string {
	return m.table
}
func (m *defaultFriendRequestsModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

//	func (m *defaultFriendRequestsModel) ListNoHandler(ctx context.Context, userId string) ([]*FriendRequests, error) {
//		query := fmt.Sprintf("select %s from %s where `req_uid`=? and ")
//	}
func (m *defaultFriendRequestsModel) FindByTargetId(ctx context.Context, targetId string) ([]*FriendRequests, error) {
	var resp []*FriendRequests
	query := fmt.Sprintf("select %s from %s where `req_uid`=? and `handle_result`=? order by `created_at` desc", friendRequestsRows, m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, targetId, constants.NoHandlerResult)
	if err != nil && err != ErrNotFound {
		return nil, err
	}
	return resp, nil
}
