// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friends `json:"list"`
}

type FriendPutInHandleReq struct {
	FriendReqId  string `json:"friend_req_id"`
	HandleResult int32  `json:"handle_result"`
}

type FriendPutInHandleResp struct {
}

type FriendPutInListReq struct {
}

type FriendPutInListResp struct {
	List []*FriendRequests `json:"list"`
}

type FriendPutInReq struct {
	ReqId  string `json:"req_id"`
	ReqMsg string `json:"req_msg,omitempty"`
}

type FriendPutInResp struct {
}

type FriendRequests struct {
	Id           string
	UserId       string
	ReqUid       string
	ReqMsg       string
	HandleResult int `json:"handle_result"`
}

type Friends struct {
	Id        string `json:"id,omitempty"`
	FriendUid string `json:"friend_uid"`
	Nickname  string `json:"nickname,omitempty"`
	Avatar    string `json:"avatar,omitempty"`
	Remark    string `json:"remark,omitempty"`
}
